openapi: "3.0.3"

info:
  version: 0.1.0
  title: AbterCMS API
  description: API for AbterCMS (AbterPhp, AbterGo, etc.)
  termsOfService: http://abtercms.do/terms/
  contact:
    name: AbterCMS Team
    email: team@abtercms.com
    url: https://team@abtercms.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

tags:
  - name: cms
    description: New, language-independent CMS

servers:
- url: https://abtercms.do/api

paths:
  /redirects:
    get:
      description: Retrieves a list of redirects
      operationId: listRedirects
      security:
        - abtercms_auth:
            - 'read:redirects'

    post:
      description: Creates a new redirect
      operationId: createRedirect
      security:
        - abtercms_auth:
            - 'read:redirects'
            - 'write:redirects'

  /redirects/{id}:
    get:
      description: Get an existing redirect
      operationId: getRedirect
      security:
        - abtercms_auth:
            - 'read:redirects'

    put:
      description: Update an existing redirect
      operationId: updateRedirect
      security:
        - abtercms_auth:
            - 'read:redirects'
            - 'write:redirects'

    delete:
      description: Delete an existing redirect
      operationId: deleteRedirect
      security:
        - abtercms_auth:
            - 'read:redirects'
            - 'write:redirects'


  /templates:
    get:
      description: Retrieves a list of templates
      operationId: listTemplates
      security:
        - abtercms_auth:
            - 'read:templates'

    post:
      description: Creates a new template
      operationId: createTemplate
      security:
        - abtercms_auth:
            - 'read:templates'
            - 'write:templates'

  /templates/{id}:
    get:
      description: Get an existing template
      operationId: getTemplate
      security:
        - abtercms_auth:
            - 'read:templates'

    put:
      description: Update an existing template
      operationId: updateTemplate
      security:
        - abtercms_auth:
            - 'read:templates'
            - 'write:templates'

    delete:
      description: Delete an existing template
      operationId: deleteTemplate
      security:
        - abtercms_auth:
            - 'read:templates'
            - 'write:templates'


  /pages:
    get:
      description: Retrieves a list of pages
      operationId: listPages
      security:
        - abtercms_auth:
            - 'write:pages'

    post:
      description: Creates a new page
      operationId: createPage
      security:
        - abtercms_auth:
            - 'read:pages'
            - 'write:pages'

  /pages/{id}:
    get:
      description: Get an existing page
      operationId: getPage
      security:
        - abtercms_auth:
            - 'read:pages'

    put:
      description: Update an existing page
      operationId: updatePage
      security:
        - abtercms_auth:
            - 'read:pages'
            - 'write:pages'

    delete:
      description: Delete an existing page
      operationId: deletePage
      security:
        - abtercms_auth:
            - 'read:pages'
            - 'write:pages'

  /pages/{id}/activations:
    post:
      description: Activate an existing page
      operationId: activatePage
      security:
        - abtercms_auth:
            - 'read:pages'
            - 'write:pages'

  /pages/{id}/inactivations:
    post:
      description: Inactivate an existing page
      operationId: inactivatePage
      security:
        - abtercms_auth:
            - 'read:pages'
            - 'write:pages'

components:
  securitySchemes:
    abtercms_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://petstore.swagger.io/api/oauth/dialog'
          scopes:
            'write:redirects': modify redirects
            'read:redirects': read redirects
            'write:templates': modify templates
            'read:templates': read templates
            'write:pages': modify pages
            'read:pages': read pages
    api_key:
      type: apiKey
      name: api_key
      in: header
