// Code generated by mockery v2.20.0. DO NOT EDIT.

package redirect

import (
	context "context"

	pkgredirect "github.com/abtergo/abtergo/pkg/redirect"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, redirect
func (_m *Service) Create(ctx context.Context, redirect pkgredirect.Redirect) (pkgredirect.Redirect, error) {
	ret := _m.Called(ctx, redirect)

	var r0 pkgredirect.Redirect
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pkgredirect.Redirect) (pkgredirect.Redirect, error)); ok {
		return rf(ctx, redirect)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pkgredirect.Redirect) pkgredirect.Redirect); ok {
		r0 = rf(ctx, redirect)
	} else {
		r0 = ret.Get(0).(pkgredirect.Redirect)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pkgredirect.Redirect) error); ok {
		r1 = rf(ctx, redirect)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Service_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - redirect pkgredirect.Redirect
func (_e *Service_Expecter) Create(ctx interface{}, redirect interface{}) *Service_Create_Call {
	return &Service_Create_Call{Call: _e.mock.On("Create", ctx, redirect)}
}

func (_c *Service_Create_Call) Run(run func(ctx context.Context, redirect pkgredirect.Redirect)) *Service_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pkgredirect.Redirect))
	})
	return _c
}

func (_c *Service_Create_Call) Return(_a0 pkgredirect.Redirect, _a1 error) *Service_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Create_Call) RunAndReturn(run func(context.Context, pkgredirect.Redirect) (pkgredirect.Redirect, error)) *Service_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, oldETag
func (_m *Service) Delete(ctx context.Context, id string, oldETag string) error {
	ret := _m.Called(ctx, id, oldETag)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, oldETag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Service_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - oldETag string
func (_e *Service_Expecter) Delete(ctx interface{}, id interface{}, oldETag interface{}) *Service_Delete_Call {
	return &Service_Delete_Call{Call: _e.mock.On("Delete", ctx, id, oldETag)}
}

func (_c *Service_Delete_Call) Run(run func(ctx context.Context, id string, oldETag string)) *Service_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Service_Delete_Call) Return(_a0 error) *Service_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *Service_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *Service) Get(ctx context.Context, id string) (pkgredirect.Redirect, error) {
	ret := _m.Called(ctx, id)

	var r0 pkgredirect.Redirect
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (pkgredirect.Redirect, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) pkgredirect.Redirect); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(pkgredirect.Redirect)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Service_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Service_Expecter) Get(ctx interface{}, id interface{}) *Service_Get_Call {
	return &Service_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *Service_Get_Call) Run(run func(ctx context.Context, id string)) *Service_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_Get_Call) Return(_a0 pkgredirect.Redirect, _a1 error) *Service_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Get_Call) RunAndReturn(run func(context.Context, string) (pkgredirect.Redirect, error)) *Service_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *Service) List(ctx context.Context, filter pkgredirect.Filter) ([]pkgredirect.Redirect, error) {
	ret := _m.Called(ctx, filter)

	var r0 []pkgredirect.Redirect
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pkgredirect.Filter) ([]pkgredirect.Redirect, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pkgredirect.Filter) []pkgredirect.Redirect); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkgredirect.Redirect)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pkgredirect.Filter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Service_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter pkgredirect.Filter
func (_e *Service_Expecter) List(ctx interface{}, filter interface{}) *Service_List_Call {
	return &Service_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *Service_List_Call) Run(run func(ctx context.Context, filter pkgredirect.Filter)) *Service_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pkgredirect.Filter))
	})
	return _c
}

func (_c *Service_List_Call) Return(_a0 []pkgredirect.Redirect, _a1 error) *Service_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_List_Call) RunAndReturn(run func(context.Context, pkgredirect.Filter) ([]pkgredirect.Redirect, error)) *Service_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, redirect, oldETag
func (_m *Service) Update(ctx context.Context, id string, redirect pkgredirect.Redirect, oldETag string) (pkgredirect.Redirect, error) {
	ret := _m.Called(ctx, id, redirect, oldETag)

	var r0 pkgredirect.Redirect
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, pkgredirect.Redirect, string) (pkgredirect.Redirect, error)); ok {
		return rf(ctx, id, redirect, oldETag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, pkgredirect.Redirect, string) pkgredirect.Redirect); ok {
		r0 = rf(ctx, id, redirect, oldETag)
	} else {
		r0 = ret.Get(0).(pkgredirect.Redirect)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, pkgredirect.Redirect, string) error); ok {
		r1 = rf(ctx, id, redirect, oldETag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Service_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - redirect pkgredirect.Redirect
//   - oldETag string
func (_e *Service_Expecter) Update(ctx interface{}, id interface{}, redirect interface{}, oldETag interface{}) *Service_Update_Call {
	return &Service_Update_Call{Call: _e.mock.On("Update", ctx, id, redirect, oldETag)}
}

func (_c *Service_Update_Call) Run(run func(ctx context.Context, id string, redirect pkgredirect.Redirect, oldETag string)) *Service_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(pkgredirect.Redirect), args[3].(string))
	})
	return _c
}

func (_c *Service_Update_Call) Return(_a0 pkgredirect.Redirect, _a1 error) *Service_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Update_Call) RunAndReturn(run func(context.Context, string, pkgredirect.Redirect, string) (pkgredirect.Redirect, error)) *Service_Update_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
